
#    _____  ______ _____  ______    _____  _____ _____  ______ ______ _   _
#   |  __ \|  ____|  __ \|  ____|  / ____|/ ____|  __ \|  ____|  ____| \ | |
#   | |__) | |__  | |  | | |__    | (___ | |    | |__) | |__  | |__  |  \| |
#   |  _  /|  __| | |  | |  __|    \___ \| |    |  _  /|  __| |  __| | . ` |
#   | | \ \| |____| |__| | |____   ____) | |____| | \ \| |____| |____| |\  |
#   |_|  \_\______|_____/|______| |_____/ \_____|_|  \_\______|______|_| \_|

# Website: www.redescreen.com
# Discord: discord.gg/redescreen

# Configuração responsáveis pelos sistemas globais do plugin "ScreenEssentials".
settings:

  # Seção de configuração específica do sistema de envio de mensagens automáticas para os jogadores presentes no servidor.
  auto-messaging:
    # Tempo de intervalo entre o envio das mensagens pelo plugin (em segundos).
    interval: 45
    # Boolean de envio randômico pelo plugin (valores possíveis: true = aleatório / false = sequenciamento).
    random: true

    # Seção de configuração dos sons utilizados nos anúncios enviados pelo sistema.
    sound-settings:
      enable-sounds: true
#      sound-type: "level_up" # (Sons disponíveis: 'villager', 'level_up'...)

messages:
  # Mensagens as quais serão enviadas pelo sistema (caso o envio seja feito de maneira aleatória, a sequência não será necessariamente seguida pelo sistema).
  informative-messages:
    - "\n\n &eFa\u00E7a a sua doa\u00E7\u00E3o!\n\n \n\n &fAjude o servidor a manter-se online adquirindo um de nossos\n &fpacotes dispon\u00EDveis em nossa loja.\n &7loja.redescreen.com\n\n "
    - "\n\n &6&lDICA: &eN\u00E3o sabe como jogar? Utilize &f/tutorial&e!\n\n "
    - "\n\n &9N\u00E3o perca nenhuma atualiza\u00E7\u00E3o!\n\n \n\n &fAcesse j\u00E1 nosso Discord e fique atualizado.\n\n &9https://discord.gg/redescreen\n\n "
    - "\n\n &dTrabalhe conosco!\n\n \n\n &fAuxilie os jogadores de nossa comunidade e contribua para que\n &fse torne cada vez melhor.\n &7https://discord.gg/redescreen\n\n "
    - "\n\n &4Proteja sua conta!\n\n \n\n &fNossa equipe jamais solicitar\u00E1 algum dado de sua conta\n (lembre-se &fde usar uma senha segura e diferente de outros servidores!\n\n \n\n &fTroque sua senha regularmente com: &7/mudarsenha&f.\n\n "
    - "\n\n &bM\u00E9todos de Pagamento\n\n \n\n &fAceitamos diversos m\u00E9todos de pagamento em nossa loja online,\n sendo eles:\n &8@ &7Mercado Pago, PagSeguro, PayPal, PIX, PicPay, Ifood Giftcard e\n &7MB Way.\n\n \n\n &8^ &fNossa loja: &bloja.redescreen.com\n &8^ &fPara Ifood Giftcard e MB Way: &bhttps://discord.gg/redescreen\n    &7(Voc\u00EA deve abrir um ticket relacionado a compras)\n\n "
    - "\n\n &d* Promo\u00E7\u00E3o de abertura &8^ &d70%!\n\n \n\n  &dAmetista (30 dias) &fa &8&mR$50,70 &715,21\n\n  &9Safira (90 dias) &fa &8&mR$184,7 &755,41\n\n  &cRubi (eterno) &fa &8&m352,7 &7105,81\n\n  &aEsmeralda (30 dias) &f &8&m168,7 &750,61\n\n \n\n &fCupom: &7ABERTURA\n &fAproveite a promo\u00E7\u00E3o em: &dloja.redescreen.com\n\n "

  # Mensagens responsáveis por definirem a descrição ("MOTD") do servidor, sendo elas, para quando o servidor está disponível/aberto para os usuário e quando o servidor se encontra em manutenção, respectivamente.
  server-description:
    # Servidor disponível para jogar (WHITELIST OFF)...
    able-to-play: "        &6&lSCREEN &8^ &fdiscord.redescreen.com\n  &eNova atualiza\u00E7\u00E3o: &f&lO FIM DO P2W! &eVenha jogar."
    # Servidor em manutenção (WHITELIST ON)...
    maintenance: "        &6&lSCREEN &8^ &fdiscord.redescreen.com\n  &c&lMANUTEN\u00C7\u00C3O: &fo melhor est\u00E1 por vir, aguarde..."